#!/bin/bash

RUN_SESSION=20211207
PREFIX="unibo-demo"

GCP_PROJECT="formazione-stefano-romanazzi"

GCS_BUCKET_NAME=${PREFIX}-data-bucket-${RUN_SESSION}
GCS_BUCKET_ZONE=europe-west1
GCS_BUCKET_CLASS=regional

BIGQUERY_DATASET_NAME=${PREFIX//-/_}_${RUN_SESSION}
BIGQUERY_DATASET=regional
BIGQUERY_ZONE=europe-west1

DATAPROC_CLUSTER_NAME=unibo-dataproc-cluster-${RUN_SESSION}
DATAPROC_CLUSTER_REGION=europe-west1
DATAPROC_CLUSTER_ZONE=europe-west1-d
DATAPROC_SCALEUP_TO_NUMWORKERS=50
DATAPROC_SCALEDOWN_TO_NUMWORKERS=2